name: Docker Build
on:
  pull_request:
    branches:
      - devbranch

  push:
    branches:
      - devbranch
jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker container
        run: docker build -t ragdemo .